import type { Metadata } from "next";
import { Hedvig_Letters_Serif } from "next/font/google";
import "./globals.css";
import { Nav } from "./ui/Nav";

const hedvig = Hedvig_Letters_Serif({
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${hedvig.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}<Nav /></body>
    </html>
  );
}
